create table databasechangelog
(
    id            varchar(255) not null,
    author        varchar(255) not null,
    filename      varchar(255) not null,
    dateexecuted  timestamp    not null,
    orderexecuted integer      not null,
    exectype      varchar(10)  not null,
    md5sum        varchar(35),
    description   varchar(255),
    comments      varchar(255),
    tag           varchar(255),
    liquibase     varchar(20),
    contexts      varchar(255),
    labels        varchar(255),
    deployment_id varchar(10)
);

alter table databasechangelog
    owner to postgres;

create table databasechangeloglock
(
    id          integer not null
        primary key,
    locked      boolean not null,
    lockgranted timestamp,
    lockedby    varchar(255)
);

create table category
(
    id   integer generated by default as identity
        primary key,
    name varchar(255) not null
        unique
);

create table person
(
    id            integer generated by default as identity
        primary key,
    username      varchar(100) not null,
    year_of_birth integer      not null,
    password      varchar      not null,
    phone         char(11)     not null,
    role          varchar(100) not null,
    created_at    timestamp
);

create table product
(
    product_id  integer generated by default as identity
        primary key,
    title       varchar(255)   not null,
    description text,
    category_id integer        not null
        constraint fk_product_category
            references category,
    price       numeric(19, 2) not null,
    quantity    integer        not null,
    image       varchar(255)   not null,
    created_at  timestamp,
    created_who varchar
);


create table person_product
(
    id         integer generated by default as identity
        primary key,
    person_id  integer not null
        constraint fk_person_product_person
            references person
            on delete cascade,
    product_id integer not null
        constraint fk_person_product_product
            references product
);

